FROM openjdk:11.0.7-jre-buster
VOLUME /tmp
ARG JAR_FILE=./target/*.jar
COPY ${JAR_FILE} /usr/heal/heal.jar
WORKDIR /usr/heal
#RUN java -jar heal.jar
ENTRYPOINT ["java","-jar","heal.jar"]
EXPOSE 8080:8080